modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "wilderflowers"
displayName = "Wilder Flowers"
version = "${version}"
displayURL = "https://modrinth.com/mod/wilder-flowers"
modURL = "https://modrinth.com/mod/wilder-flowers"
issueTrackerURL = "https://github.com/cassiancc/Wilder-Flowers/issues"
logoFile = "assets/wilderflowers/logo.png"
authors = "cassiancc, Kobber, ProbablyEkho, DavigJ"
description = '''
Adds various wildflowers, clover patches, and flower garlands. Revel in nature's boutique!
'''

[[dependencies.wilderflowers]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.181,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wilderflowers]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"

[[mixins]]
config = "wilderflowers.mixins.json"